// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMrHABw0GG0DrXL8LYm-rI6TSzSI5pBow',
    appId: '1:263171351553:web:8b35fcef4e09e079d3cc00',
    messagingSenderId: '263171351553',
    projectId: 'score-board-detect',
    authDomain: 'score-board-detect.firebaseapp.com',
    storageBucket: 'score-board-detect.appspot.com',
    measurementId: 'G-JJY8N3XMXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwIyyTEgwIbu3Y8msD8DXjNbh7I0FXiIE',
    appId: '1:263171351553:android:df60eae3d4b698b1d3cc00',
    messagingSenderId: '263171351553',
    projectId: 'score-board-detect',
    storageBucket: 'score-board-detect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxtdYN_Fz0o6pNHjR7hQ68m4D4HyiXnYo',
    appId: '1:263171351553:ios:b5f76004c44598e5d3cc00',
    messagingSenderId: '263171351553',
    projectId: 'score-board-detect',
    storageBucket: 'score-board-detect.appspot.com',
    iosClientId:
        '263171351553-5rq54j1vsjmvbdflrn9ebbc5q8p0ijf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.scoreBoardDetect',
  );
}
